### ISSUE TITLE
Issues with quarterly dates

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#11]
File: https://github.com/epogrebnyak/cbr-db/blob/master/py3/cli_dates.py

- [x] refactor code as suggested in lines 51-65
- [x] get_last_date_in_year() must be sensisitve to 'form', for form 102 this must be last quarter of year available, not last month 
- [x] ```python bankform.py unpack 102 2014q4 2015``` contains 2015-03-01 date which is not end of quarter get_date_range_from_command_line(args) msut also be sensitive to 'form'  and return end of quarters only for from 102. 
- [x] very wrong behaviour of *make csv* with two timestamps below - it should process files for 2014q4 and 2015q1, istaed it attemps to prcess 2015q1 for three times and tries reading unexisting files. 

```
D:\databases\cbr-db-master\py3>python bankform.py make csv 102 2014q4 2015

Date: 2015-01-01
File 02015_P1.DBF not found
File 02015_P.DBF not found

Date: 2015-02-01
File 02015_P1.DBF not found
File 02015_P.DBF not found

Date: 2015-03-01
File 02015_P1.DBF not found
File 02015_P.DBF not found

Date: 2015-04-01
Converting 12015_P1.DBF to csv file bulk_f102_P1.12015_P1
Time elapsed: 0:00:48.513867
Converting 12015_P.DBF to csv file bulk_f102_P.12015_P
Time elapsed: 0:00:00.452235

Date: 2015-05-01
Converting 12015_P1.DBF to csv file bulk_f102_P1.12015_P1
Time elapsed: 0:00:48.014850
Converting 12015_P.DBF to csv file bulk_f102_P.12015_P
Time elapsed: 0:00:00.452234

Date: 2015-06-01
Converting 12015_P1.DBF to csv file bulk_f102_P1.12015_P1
Time elapsed: 0:00:47.780936
Converting 12015_P.DBF to csv file bulk_f102_P.12015_P
Time elapsed: 0:00:00.436640
```

**Comment by repo2156** [comment]
This should be fixed in the last commits.

form102 and its quarterly notation required many changes / special cases in cli_dates.py. I've enhanced the test cases  with the new functions / functionality.

**Comment by repo2156** [comment]
Evgeny,

I've kept my implementation of the quarter string parser, but I've added commentaries to explain the code. When I was implementing the function for the first time, I've started by finding the position of 'q' or 'Q' as you also suggested, but it turned to be less maintainable than the current one.

**Comment by epogrebnyak** [comment]
TODO (EP): some docstring editing, almost finished.

**Comment by epogrebnyak** [comment]
Todo in https://github.com/epogrebnyak/cbr-db/commit/bda01c049bf74d5c00418a4289b97b3bc71bbb1a

**Comment by epogrebnyak** [comment]
Not todo/alternative: 
- [ ] may use regex to catch year/quarter in get_date_from_quarter_string()

Minor issues: 
- [ ] allows future dates in form 102 and crashes on a future date in 101.

Other issues cleared.
