### ISSUE TITLE
Minor: update requirements.txt

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#12]
Seems not all used packages are listed in requirements.txt

**Comment by repo2156** [comment]
Updated. To guarantee that the exact versions that were specified are correct, we should test it in an isolated/virtual environment.

I think we should wait for the pandas interface to be completed so we can test all libraries at the same time, avoiding repeated work.

**Comment by epogrebnyak** [comment]
There is also some work going on with flask interface - so that should add to requirements too. I close the issue for now, but testing in virtualenv/new machine will be an issue
