### ISSUE TITLE
Legacy error in f102_part_*

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#13]
f102_part_p1 and f102_part_p remain hardcoded in regn. They must be similar to f101_part_\* and depend on 'cfg_regn_in_focus' and 'cfg_date_in_focus'

**Comment by repo2156** [comment]
Fixed in commit 725a72ff50aa92678c474197c0c414fa43f6c937 .
Note: I've had to restore part of the file (add `dt` and f102_part_p[1] again) as your last commit reverted the sql dumps to a previous state.
