### ISSUE TITLE
Table 'bulk_f101_b' deleted from raw database

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#14]
Need restore table 'bulk_f101_b' in raw database.

**Comment by epogrebnyak** [comment]
Table 'bulk_f101_b' is not present in the database after I do following sequence:
- download zip file from repo
- run ```python bankform.py reset database```

**Comment by epogrebnyak** [comment]
Suspicios of: 

>"It is the first table to be created when loading the dump." 

When running csv import no tables are created. Data is imported to existing tables. 

Comment if I'm wrong on somethng.

**Comment by repo2156** [comment]
Hi,

*python bankform.py database reset raw* loads the database strucuture from sql dumps, where the tables are created. As you can see here: https://github.com/epogrebnyak/cbr-db/blob/master/database/db_dump/dbf_db3.sql, 'bulk_f101_b' is the first table that is created when issuing a database reset.

Maybe your local *db_dump/dbf_db3.sql* was modified? You can try to restore it to the last repo version by removing your local file and running "git pull".

**Comment by epogrebnyak** [comment]
Will check tomorrow - thanks for commenting. Likely it is local issue with my dump.

**Comment by epogrebnyak** [comment]
A problem caused by wrong representation of tables in HeidiSQL client tree view. Solved by deleting database in cleint and restoring using bankform.py command.
