### ISSUE TITLE
Part of code running on new server 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#17]
![image](https://cloud.githubusercontent.com/assets/9265326/8545827/1c47ae5e-24bb-11e5-93e4-2f7df98f9761.png)

**Comment by repo2156** [comment]
Are you sure you are running it with Python 3? Pep 0263 refers to unicode support on Python 2.

Try running with: python3 bankform.py ....

**Comment by epogrebnyak** [comment]
```python3 bankform.py``` works on debian
