### ISSUE TITLE
Deployment to remote server - 7z/unrar path

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#18]
Path to zip/rar - different on windows (inside project directory) and linux (usr/bin/unrar)

Todo:
- make a bash script to install 7z and unrar using ```apt install```
- in global_ini.py select differen paths in Linux and Windows environment

See discussion on https://github.com/Nikola-K/flask_cbr/issues/1

**Comment by epogrebnyak** [comment]
Next: https://github.com/epogrebnyak/flask_cbr/blob/master/comment/cbr-db-deployment-advice.md

**Comment by repo2156** [comment]
The path selection, with default paths being automatically chosen according to the operating system has been implemented.

**Comment by epogrebnyak** [comment]
Also pending: make a bash script to install 7z and unrar using ```apt install```.

**Comment by epogrebnyak** [comment]
```
apt-get install unrar
apt-get install 7z
```
