### ISSUE TITLE
execute_sql() fails in database.py

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#20]
```execute_sql(u"INSERT IGNORE INTO `bank` (`regn`, `regn_name`) VALUE (964, 'Внешэкономбанк')", db)``` does not insert a row for unknown reason. 

Command line call:
```python bankform.py import bank```

Desired output:
```use cbr_db3; select * from bank where regn = 964;```
must return one row

**Comment by repo2156** [comment]
I've found the culprit: by default, pymsql does not commits after SQL execution. Forcing a conn.commit() after running the SQL solves the issue. I've reverted the call to execute_sql() as it now works as expected for insertions too.

Running

    use cbr_db3; select * from bank where regn = 964;

returns one row.

**Comment by epogrebnyak** [comment]
I see this https://github.com/epogrebnyak/cbr-db/commit/ea1c268206ab7f185f547ab799782f156bdd0945 adds a conn.commit()

Not tested on my side, but hopefully works.
