### ISSUE TITLE
Separate directory structrue configuration from global_ini.py (config_folders.py)

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#21]
In https://github.com/epogrebnyak/cbr-db/blob/config-folders/py3/config_folders.py
Review implemnetation :
- [x]   config of data directories using settings.cfg  (IMPLEMENTED)

Implement as commented in 'todo' in code:
- [x]   specify path to archive executables using settings.cfg  (NOT IMPLEMENTED)
- [x]   specify paths to mysql using settings.cfg (NOT IMPLEMENTED)

**Comment by repo2156** [comment]
Evgeny,

I've implemented the path selection in settings.cfg. Defaults were provided, selecting the path depending on the operating system. I've tested it by moving all paths (including unrar and 7zip) to a directory outside the project folder.

In the process, I've fixed some bugs present in `config_folders.py` too.

I've made all the changes needed to use the new config_folders, such as removing old code from global_config and using get_output_dir().

There are 2 new TODOS that I've identified:

1. The private textual data can't be found anymore as the old directory structure separated them by years. This is a known issue and must be fixed before --private-data flag works again.

2. mysql / mysqlimport executables are called in the program. To make it portable, it should also be configured (can have different names in Windows and Linux).

I've pushed my changes to the config-folders branch, and all basic operations are working.

**Comment by epogrebnyak** [comment]
I disagree on: 

> The private textual data can't be found anymore as the old directory structure separated them by years. This is a known issue and must be fixed before --private-data flag works again.

- browsing by year is still implemented in https://github.com/epogrebnyak/cbr-db/blob/config-folders/py3/private_form_txt.py#L90 
- get_private_data_folder(form, subfolder_tag) still has the same interface
- annual subdirectories can be still be part of private data folder

Why exactly --private-data flag may not work?

**Comment by epogrebnyak** [comment]
Valid:

> mysql / mysqlimport executables are called in the program. To make it portable, it should also be configured (can have different names in Windows and Linux).

However it seems they are the same names in Win and Linux, so they just work by coincidence. Can keep as it is for now.

**Comment by epogrebnyak** [comment]
Can you merge this branch to master?
