### ISSUE TITLE
List risks in vulnerabilitites.txt

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#23]
Make a list concerns/risks/unusual behaviours-cases/hardcoded parts/tradeoffs by adding to 
https://github.com/epogrebnyak/cbr-db/blob/master/issues/risks/vulnerabilitites.txt

Go over open and closed issues and copy any remarks that relate to risks/vulnerabilities of the existing iplementation.

**Comment by epogrebnyak** [comment]
Can you oraginise https://github.com/epogrebnyak/cbr-db/blob/master/issues/risks/vulnerabilitites.txt#L4-L44 by into some subsections (e.g. 'general issues', 'data extraction', 'validation' - of your choice)?

**Comment by repo2156** [comment]
Done.

I've organized and renamed the file as indicated. Now I see that database.py may has too many responsibilities, as the most command line invocations are handled by it.

**Comment by epogrebnyak** [comment]
Move file to  to https://github.com/epogrebnyak/cbr-db/wiki/Issues,-risks,-vulnerabilities. See also https://github.com/epogrebnyak/cbr-db/wiki/Python-file-structure
