### ISSUE TITLE
Need baf.sh

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#26]
As described in https://github.com/epogrebnyak/cbr-db/blob/master/py3/baf.bat

**Comment by epogrebnyak** [comment]
Possible feature: baf.sh/bat can also distinguish if python3 or python executable is present.

**Comment by repo2156** [comment]
Done.

In GNU/Linux, where baf.sh will be used, python3 will always point to Python 3.X, and python2 to Python 2 (the discrepancies occurs with just 'python').
