### ISSUE TITLE
create autogenerated documentation

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#27]
Use http://sphinx-doc.org/

**Comment by repo2156** [comment]
Done. With sphinx installed, run make.bat from the docs folder and the documentation will be located in docs/build/index.html .

TODO: autoconvert the README.md to README.rst, avoiding the manual rewrite at each edit (as sphinx uses rst, not markdown files).

**Comment by epogrebnyak** [comment]
Should make.bat be part of this repo or sphynx installation?

**Comment by epogrebnyak** [comment]
Was able to run, browser documentation.
