### ISSUE TITLE
Parse regn from private txt files and write 'regn' to csv file

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#29]
See comments in e-mail.

**Comment by epogrebnyak** [comment]
Placeholder for parsing 
https://github.com/epogrebnyak/cbr-db/blob/master/py3/private_form_txt.py#L97-L102

**Comment by repo2156** [comment]
Parsing function implemented.

I've initially tried using the suggested anchor, but due to encoding issues I think that the current implementation should be more robust.

**Comment by epogrebnyak** [comment]
Maybe also limit the serach to first, say 20 lines of file?

**Comment by repo2156** [comment]
Good idea, implemented.
