### ISSUE TITLE
Enable processing of form 102

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#3]
Enable functionality of test-one-date-102.bat.

**Comment by repo2156** [comment]
Support for form 102 has been added from the *reset database* to the *migrate database* command. I'm waiting for criticism / review.

**Comment by epogrebnyak** [comment]
The only enhancement I can think of is to implement f102_make_dataset() procedure and link it to ```make dataset 102``` command.

f102_make_dataset()  described in coomment to following commit:
https://github.com/epogrebnyak/cbr-db/commit/969ba5b95f7260406b380db46b11e00bfcd1fa02

**Comment by repo2156** [comment]
Implemented.
