### ISSUE TITLE
Date (field dt) not written to f102 bulk tables  

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#30]
- [x] https://github.com/epogrebnyak/cbr-db/blob/master/py3/make_csv.py#L59 apparently adds date to 
csv file
- [x] bulk_f102_p and bulk_f102_p1 do not have 'dt' field

I may have overwritten dbf_db.sql, so need to restore table structure with 'dt' field for bulk_f102_p and bulk_f102_p1. 

There other additions to dbf_db.sql, so must just add these former changes to new  dbf_db.sql.

**Comment by repo2156** [comment]
The dbf_db.sql that is in the repository still contains the date: https://github.com/epogrebnyak/cbr-db/blob/master/database/db_dump/dbf_db.sql#L90 .

I've tested it locally with git HEAD and the column `dt` is present on the database.

You can restore your local files by issuing a reset or by removing them and using `git pull` again.

**Comment by epogrebnyak** [comment]
Will test that, thanks for pointing out.
