### ISSUE TITLE
date2quarter() wrong behaviour

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#31]
https://github.com/epogrebnyak/cbr-db/blob/master/py3/date_engine.py#L147-L159

where is function used?

**Comment by repo2156** [comment]
Hi,

It is used in `write_csv_by_path` in make_csv.py. I've saw your comments, but the function did what I thought was right. Lets see the following example:

2014-12-01 -> I've thought that the 4-th quarter would end at 2015-01-01, no? 
At my understanding, this would still be in the 3-th quarter of 2014.

Could you confirm this? I will change it quickly after you confirmation.

**Comment by epogrebnyak** [comment]
The fucntins returns (2014, 3) for date '2014-12-01' which appears as nonsense. It undermines credinility about his functionan, because it works rigth only for 4 dates a year, otherwise the fucntion output is not meaningful. If you want to stick to this function better return None for moths which are not quertaer reporting dates. Alternatively use conv_date2quarter()

**Comment by repo2156** [comment]
Hi,

Maybe a better name would be convert_date_to_last_completed_quarter.

The semantics are different than conv_date2quarter(); date2timestamp needs the current behavior to work with form102 files. I've changed the docstring to reflect this and the function will now raise an exception if the month than the four end of quarted dates (months 1, 4, 7, 10).

I've commited the changes to the repository.

**Comment by epogrebnyak** [comment]
Better comment with commit - easier to follow. Eg changed in 65d5d3f599b932a31649e5e8442a94324e0dfd0c

**Comment by epogrebnyak** [comment]
Better, but not fully convincing. 

- convert_date_to_last_completed_quarter sounds better
- what you call `end-of-quarter month (months 1, 4, 7, 10) ` in docstrings is not end of quarter. These are months of quarter reporting dates. End of quater is 3,6,9,12.

I've put it in https://github.com/epogrebnyak/cbr-db/wiki/Issues,-risks,-vulnerabilities.
