### ISSUE TITLE
Wrong wiki page

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#35]
Delete https://github.com/epogrebnyak/cbr-db/wiki/Identified-vulnerabilities
Put all additions into existing https://github.com/epogrebnyak/cbr-db/wiki/Identified-vulnerabilities

**Comment by epogrebnyak** [comment]
Note https://github.com/epogrebnyak/cbr-db/wiki/Issues,-risks,-vulnerabilities was edited ny me before.

**Comment by repo2156** [comment]
I've merged vulnerabilities.md with the wiki page (both have the most updated contents).

**Comment by epogrebnyak** [comment]
Accepted
