### ISSUE TITLE
Change date/regn truncation procedure in sql, add cli interface

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#4]
Add explicit regn and date limit definition when truncating raw database (now hardcoded in database sql statements). Run make-reference-dataset.bat to intilialise database.

## Part 1. Command line
Command line must pass a list of reginstration numbers (regn) and dates into correstonding tables in dbf_db3 database. These tables are *cfg_regn_in_focus* and *cfg_date_limit*. To put some values to work with run before command line is implemented run *temp_init_truncation_limits*
```
    bankform.py make dataset <FORM> timestamp1 [timestamp2] (--regn=<regn_list> | --regn-file<file>)
    bankform.py make dataset <FORM> 2015 --regn=956,1000 --regn-file regn.txt 
        must look for regn.txt in current directory or DIRLIST['global']['tables']
```
## Part 2. SQL
* Will add description here. *
        now regn list is hard-coded in views f101_* (e.g. f101_long)
        dates are hard-coded too
        need [selected_date] * [selected_regn]

**Comment by epogrebnyak** [comment]
## CLI (update)
```
Usage string:
bankform.py make dataset <FORM> timestamp1 [timestamp2] [--regn=<regn_list> | --regn-file <file> | --regn-all]

Example:
bankform.py make dataset <FORM> 2015 
bankform.py make dataset <FORM> 2015 -–regn-all
bankform.py make dataset <FORM> 2015 --regn=956,1000 
bankform.py make dataset <FORM> 2015 --regn-file regn.txt 

Desired behaviour:
        must look for regn.txt in current directory or DIRLIST['global']['tables']
           regn.txt will contain one regn per line
        must unpack --regn=956,1000
        both variants result in regn list, to be written to cfg_regn_in_focus
        start and end date go to cfg_date_limit.

Not sure:
        How do we pass –-regn-all to database? If there is a list of regn it goes to cfg_regn_in_focus but -–regn-all must put all regn in cfg_regn_in_focus. Maybe put all existing regn from all bulk forms to cfg_regn_in_focus by default and overwrite them if [--regn=<regn_list> | --regn-file <file> is provided. 
```

**Comment by epogrebnyak** [comment]
## Part 2. SQL
For form 101 there is a much faster assembly procedure f101_make_dataset().

**Comment by repo2156** [comment]
I need some clarification on the desired behavior. Please check if I understood it correctly:

A call to

$ bankform.py make dataset 101 2015-01 2015-02 --regn=100,101,102

will:

1. Clear the table cfg_regn_in_focus
2. Clear the table cfg_date_limit
3. Insert the rows 100, 101, and 102 to cfg_regn_in_focus
4. Insert the row 2015-01-01, 2015-02-1 to cfg_date_limit

Right?

I do not see where `cfg_date_in_focus` will be set. It is used in the views to the bulk table, but as this table is empty, the views do not contains nothing.

**Comment by epogrebnyak** [comment]
A call to 
```bankform.py make dataset 101 2012-01 2015-02 --regn=100,101,102```
(changed timestamp)
for the regn will:
- Clear the table cfg_regn_in_focus
- Insert the rows 100, 101, and 102 to cfg_regn_in_focus

For the dates:
- Clear the table cfg_date_limit
- Insert the row 2012-01-01, 2015-02-01 to cfg_date_limit
- **Run database-stored procedure cfg_init_populate_dates()** (it takes all available dates in form 101 and between 'cfg_date_limit' dates and writes them to cfg_date_in_focus)
OR 
- Insert dates directly from python script - we have function to make a sequence of dates, insert them to cfg_date_in_focus


Not todo: currently we are not checking if regns supplied in cli are valid.

**Comment by epogrebnyak** [comment]
About --regn-all:
invoke ```cfg_init_regn_fullset()``` - I think it is better than keeping a default list in separate file

**Comment by repo2156** [comment]
The Python code should be working now (both date and regn truncation), but there is an issue with 'cfg_init_regn_fullset(). I will try to fix it.

**Comment by repo2156** [comment]
Solved. I've changed cfg_init_regn_fullset, removing 
"select distinct regn from bulk_f101veb;", as this table does not has a regn column.

This issue is ready for testing.

**Comment by epogrebnyak** [comment]
```select distinct regn from bulk_f101veb;``` 
should be replaced with 
```select 964;```
it is intended to add one more regn number to the table.

**Comment by epogrebnyak** [comment]
There is an error running ```python bankform.py make dataset 101 2015``` while  ```python bankform.py make dataset 101 2015 --regn-all``` runs fine.

TODO: make a simple batch sequence to test functionality of command-line calls
```
python bankform.py make dataset 101 2015
python bankform.py make dataset 101 2015 --regn-all
python bankform.py make dataset 101 2015 --regn=1481,354,1000,1623,2748,3349,1326,1470,1942,2790,3340,964
python bankform.py make dataset 101 2015 --regn=964
... more 
```

**Comment by repo2156** [comment]
Fixed, all suggested tests (and regn from file) are working now.

**Comment by epogrebnyak** [comment]
OK, but what is a test that you created under 

>TODO: make a simple batch sequence to test functionality of command-line calls

is this code form my previous comment or some extension of it?

**Comment by repo2156** [comment]
Hi Evgeny,

I've modified bankorm.py, making it testable. I've added an unit test to verify the regn truncation (run from the tests folder: test_select_regn.py .

**Comment by epogrebnyak** [comment]
wontfix:

Output not fully covering what the script does (some stages omitted), must not change now.
```
d:\git\cbr-db\py3>python bankform.py make dataset 101 2015 --regn=1481,354,1000,1623,2748,3349,1326,1470,1942,2790,3340,964

Date: 2015-01-01

Date: 2015-02-01

Date: 2015-03-01

Date: 2015-04-01

Date: 2015-05-01

Date: 2015-06-01

Date: 2015-07-01

Calling:
mysql --database dbf_db3 --execute "call cfg_init_populate_dates();"
Elapsed time: 0.48

Calling:
mysql --database dbf_db3 --execute "call f101_make_dataset();"
Elapsed time: 2.09

d:\git\cbr-db\py3>
```
