### ISSUE TITLE
Scripts clean up

### ISSUE THREAD

**Issue by alexanderlukanin13** [epogrebnyak/cbr-db#46]
Do we need the following executable scripts:

1. bat files in [py3/scripts](https://github.com/epogrebnyak/cbr-db/tree/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/script)

2. [py3/utils/ini.bat](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/utils/ini.bat)

3. [py3/utils/ini.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/utils/ini.py)

4. [py3/utils/save7z.bat](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/utils/save7z.bat)

5. [py3/utils/start_unit_tests.bat](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/utils/start_unit_tests.bat)

6. [py3/utils/test-one-date.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/utils/test-one-date.py)

7. [py3/baf.bat](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/baf.bat)

8. [py3/bat.sh](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/baf.sh)

9. [py3/get_form_definition.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/get_form_definition.py)

10. [py3/pandas-interface.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/pandas-interface.py)

I'm voting for elimination of all or most bat files, and for reducing number of executable entities to a minimum.

**Comment by epogrebnyak** [comment]
- move pandas-interface to issues folder , it is todo
- baf is a shorthand maybe keep it?
- ini.py is a kind of self-check about mysql availability, need to integrate similar check to our code
- rest is history
