### ISSUE TITLE
Executable sections clean up

### ISSUE THREAD

**Issue by alexanderlukanin13** [epogrebnyak/cbr-db#47]
Do we need executable section in the following files:

1. [py3/cli_dates.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/cli_dates.py#L194-L199)

2. [py3/date_engine.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/date_engine.py#L151-L163)

3. [py3/make_url.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/make_url.py#L65-L69)

4. [py3/make_xlsx.py](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/make_xlsx.py#L94-L109)

5. [py3/terminal](https://github.com/epogrebnyak/cbr-db/blob/5f10fcbe4a7347364154125ce008c73dad5fc23a/py3/terminal.py)

we can replace these sections with unit tests.

**Comment by epogrebnyak** [comment]
Executable part was for debugging, agree tests are better for this

**Comment by alexanderlukanin13** [comment]
@epogrebnyak I'll remove executable parts and add tests as a separate pull request

**Comment by alexanderlukanin13** [comment]
Everything done except `make_xls.py`
