### ISSUE TITLE
wrapper.py fails

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#57]
```
2016-02-28 01:26:06 INFO Calling ['C:\\Users\\Евгений\\Anaconda3\\python.exe', '--version']
Fatal Python error: Failed to initialize Windows random API (CryptoGen)
2016-02-28 01:26:22 ERROR Child process returned 255
```

**Comment by epogrebnyak** [comment]
the call is ```python wrapper.py dummy 101 2015```
wrapper.py seems a bit overengineered

**Comment by alexanderlukanin13** [comment]
Fixed in `master`, please test.

> wrapper.py seems a bit overengineered
There's nothing sophisticated, just a batch execution. Anyway, it's not designed to be a permanent solution. I recommend creating a new user-friendly goal-oriented interface from scratch, as I described in upwork message.
