### ISSUE TITLE
ERROR 1449 (HY000) at line 1: The user specified as a definer ('test_user'@'%') does not exist

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#61]
I have `test_user` in MySQL but cannot pass a definer.

**Comment by alexanderlukanin13** [comment]
@epogrebnyak  Please check the user host with the following command (should be %):

    SELECT host, user FROM mysql.user;

You can also try to re-create user:

    DROP USER test_user;
    CREATE USER test_user IDENTIFIED BY 'test_password';
    GRANT ALL PRIVILEGES ON dbf_db.* TO test_user;
    GRANT ALL PRIVILEGES ON cbr_db.* TO test_user;
    GRANT FILE ON *.* TO test_user;

**Comment by epogrebnyak** [comment]
Thanks for the code, will try re-creating the user.

**Comment by epogrebnyak** [comment]
What if host is not '%'? Relogin?

**Comment by alexanderlukanin13** [comment]
@epogrebnyak What do you see in `mysql.user` after re-creating `test_user`?

**Comment by epogrebnyak** [comment]
Fixed by running:
```sql
CREATE USER test_user IDENTIFIED BY 'test_password';
GRANT ALL PRIVILEGES ON dbf_db.* TO test_user;
GRANT ALL PRIVILEGES ON cbr_db.* TO test_user;
GRANT FILE ON *.* TO test_user;
```

before that had: 

```
host;user
127.0.0.1;root
localhost;excel
localhost;pma
localhost;root
localhost;test_user
````

after "Create user" script:
```
host;user
%;test_user
127.0.0.1;root
localhost;excel
localhost;pma
localhost;root
localhost;test_user
```
