### ISSUE TITLE
if behind firewall, do not invoke download 

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#8]
if behind firewall, do not invoke download - catch error below (urlopen connection timed out)
  urllib.error.URLError: urlopen error  WinError 10060  Попытка установить соединение была безуспешной, т.к. от другого к
  требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже п
  компьютера

**Comment by repo2156** [comment]
The program must catch this specific exception (urllib.error.URLError) and
(1) warn the user about the firewall, stopping the process or (2) do another action?

**Comment by epogrebnyak** [comment]
The program must issue a warning (e.g. "Could not reach URL, download not started") and continue.

**Comment by repo2156** [comment]
Should be fixed by now. Could you verify if that's the desired outcome?

**Comment by epogrebnyak** [comment]
Issues warning when timed out as intended.
