### ISSUE TITLE
Direct import of data to tables 'bank', 'plan', 'sprav102' in final database.

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/cbr-db#9]
This data needs not to be truncated, so it shouldn't go to raw database, foes to final database.

Desired behaviour:
the functions read data from dbf file (generator), create sql bulk insert statement and execute it.   
functions can be called from cli interface.

Note: 
- must also add regn/name of "private data" bank(s)
- bank names imported only from form 101, assumes to be the same in other forms
- this feature allows to skip some 'import tables' commands
- user: for latest names/account always unpack latest date file (overwrites existing files)
- may use functions to bulk-insert data to table in database (see code in lines 46-100 
https://github.com/zimBop/dbfToMysql/blob/master/functions.php, - it assembles insert quesry of 500 items)

form	|	DBF file	|	database table	|	content
-----------	|	-----------	|	-----------	|	-----------
101	|	mmyyyy_N.DBF	|	bank	|	bank names
101	|	mmyyyyN1.DBF	|	bank	|	bank names
101	|	NAMES.DBF	|	plan	|	form 101 account names
102	|	SPRAV1.DBF 	|	sprav102	|	form 102 account names

*Command line syntax:*
```
bankform.py import plan <FORM> 
    imports account names (form 101 and 102) to final database
bankform.py import bank <FORM>
    imports bank names to final database (based on form 101 and private data)
```

**Comment by epogrebnyak** [comment]
Priority in the section is SPRAV1.DBF

**Comment by repo2156** [comment]
sprav1.dbf import has been implemented.

**Comment by epogrebnyak** [comment]
> sprav1.dbf import has been implemented.
what is the interface to invoke sprav1.dbf import?

**Comment by repo2156** [comment]
The refactorings were performed, except for function `get_import_dbf_path`.
Is I understood, the bank names are extracted from the latest dbf files with the pattern  mmyyyyN1.DBF and mmyyyy_N.DBF, right? So one must search for the latest file that matches these patterns in the dbf dir, isn't this right?

**Comment by repo2156** [comment]
Importing the account names for forms 101 and 102 works.
I'm waiting for clarification in the last comment to implement the bank name importing.

**Comment by epogrebnyak** [comment]
You are right about getting latest file, I forgot what the file naming pattern was there. As default behavior the program should iterate to find the latest file.  This should be linked to
```bankform.py import plan <FORM>```

Also add some message to screen like "Importing <filename> to final database." + "Done." to this import and other in this issue.  

Not todo: May also add ```bankform.py import plan <FORM> timestamp```

**Comment by epogrebnyak** [comment]
Is ```bankform.py import plan 101``` implemented (import of NAMES.DBF)?

**Comment by repo2156** [comment]
Yes, it is (importing to the new table sprav101, is this the correct name?). Today I will finish the other two.

**Comment by epogrebnyak** [comment]
NAMES.DBF should go to 'plan' table, not  sprav101 (it is a legacy name - used in sql queries, see table above)

**Comment by repo2156** [comment]
Fixed. There's a mismatch between the dbf columns and the table columns, so I've added a new configuration to global_ini.py

**Comment by repo2156** [comment]
Importing bank and account names works now. I've not handled yet the private data (described in other issue anyway).

**Comment by epogrebnyak** [comment]
> Importing bank and account names works now. 

- [ ] error in ```bankform.py import plan 101``` - new issue # 16 added 
- [ ] not implemented from above: *Also add some message to screen like "Importing <filename> to final database." + "Done." to this import and other in this issue.*
- [ ] bankform.py import bank <FORM> not implemented.
- [ ] bankform.py import plan 102 causes error, when called for the second time. 
>second call of bankform.py import plan 102 causes error (table alrady exists), need to choose from: (a) delete data from table before import (b) insert ignore or insert replace. In my opinion (a) is best for account names (plan/sprav), (b) is ok for bank names. Can do (a) for now.

I get overwhelmed to track bugs like this, it's a bit frustriting for 'Importing bank and account names works now. ' - it doesn't. 

Try before commiting un update:
```
bankform.py import plan 101
bankform.py import plan 102
bankform.py import bank 101
bankform.py import bank 102 
```
bankform.py import bank 102  must do same thing as 101, simple can ignore <FORM>, with comment in code

**Comment by epogrebnyak** [comment]
Last command executed under ```bankform.py import bank``` should be:
```
INSERT IGNORE INTO `bank` (`regn`, `regn_name`) VALUE
	(964, 'Внешэкономбанк');
```

**Comment by repo2156** [comment]
The sequence:

    python bankform.py import plan 101
    python bankform.py import plan 102
    python bankform.py import bank

is works as expected. The last command executed will depend on the current SPRAV1.dbf and NAMES.dbf, no?

**Comment by epogrebnyak** [comment]
> ast command executed will depend on the current SPRAV1.dbf and NAMES.dbf

you mean last file imported depends on which files were unpacked last, right?

**Comment by repo2156** [comment]
Yes, it currently depends on the last files that were unpacked. Is this the correct behavior or should it invoke a download of the most up-to-date files and unpack them before the import?

**Comment by epogrebnyak** [comment]
Reading last unpacked file is correct bahaviour.

**Comment by epogrebnyak** [comment]
NOT IMPLEMENTED:

Last command executed under ```bankform.py import bank``` should be:
```
INSERT IGNORE INTO `bank` (`regn`, `regn_name`) VALUE
	(964, 'Внешэкономбанк');
```

**Comment by repo2156** [comment]
Commit 6ab8804b1c4b789964b160cf6ce2bb0a8c600e3b hardcoded the insert at import bank as requested.

**Comment by epogrebnyak** [comment]
Not working. See comment to commit above. The resulting behaviour: ```select * from bank where regn = 964``` must return values, but it is empty, do not know why. Changing to ```run_sql_string(u"INSERT IGNORE INTO bank (regn, regn_name) VALUE (964, 'Внешэкономбанк')", db)```

**Comment by epogrebnyak** [comment]
https://github.com/epogrebnyak/cbr-db/commit/0e6f2a7dff6d54134db0c0c5d8814d323aa1ff48 changes insert to run_sql_string(), ```select * from bank where regn = 964``` returns one row as desired. 

Created duplicate https://github.com/epogrebnyak/cbr-db/issues/20

Current issue ready to close after https://github.com/repo2156 comments.
